import React, { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { TrendChart } from '../components/Chart';
import { MetricCard } from '../components/MetricCard';
import { PlatformBadge } from '../components/PlatformBadge';
import { SectionHeader } from '../components/SectionHeader';
import { useAnalytics, usePosts } from '../hooks/useAppData';
import { Platform } from '../types';
import { colors, globalStyles, radius, spacing } from '../theme';

const platforms: Array<Platform | 'All'> = ['All', 'Instagram', 'TikTok', 'YouTube'];
export function AnalyticsScreen() {
  const { data } = useAnalytics();
  const { data: posts } = usePosts();
  const insets = useSafeAreaInsets();
  const [platform, setPlatform] = useState<Platform | 'All'>('All');
  const [range, setRange] = useState<'7D' | '30D' | '90D'>('7D');
  const chartData = data?.points;
  return <View style={[globalStyles.screen, { paddingTop: insets.top }]}><ScrollView contentContainerStyle={globalStyles.content} showsVerticalScrollIndicator={false}><Text style={styles.eyebrow}>PERFORMANCE OVERVIEW</Text><Text style={globalStyles.h1}>Your momentum</Text><Text style={styles.subtitle}>See what's working across your connected channels.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{platforms.map((item) => <Text key={item} onPress={() => setPlatform(item)} style={[styles.filter, platform === item && styles.filterActive]}>{item}</Text>)}</ScrollView><View style={styles.metrics}><MetricCard label="Views" value="84.2k" change="↑ 24%" icon="◒" /><MetricCard label="Engagement" value="6.8%" change="↑ 1.2%" icon="♡" color={colors.lavender} /></View><View style={styles.chartCard}><View style={styles.chartHeader}><View><Text style={styles.cardLabel}>REACH OVER TIME</Text><Text style={styles.chartValue}>{data?.totalViews.toLocaleString() ?? '0'} <Text style={styles.chartChange}>+{data?.delta ?? 0}%</Text></Text></View><View style={styles.range}>{(['7D', '30D', '90D'] as const).map((item) => <Text key={item} onPress={() => setRange(item)} style={range === item ? styles.rangeActive : styles.rangeText}>{item}</Text>)}</View></View>{chartData && <TrendChart data={chartData} />}</View><SectionHeader title="Top performing posts" action="View all" /><View style={styles.topPosts}>{posts?.filter((post) => (platform === 'All' || post.platform === platform) && (post.status === 'Published' || post.status === 'Scheduled')).slice(0, 3).map((post, index) => <View key={post.id} style={styles.topPost}><Text style={styles.rank}>0{index + 1}</Text><View style={styles.topCopy}><Text numberOfLines={1} style={styles.topTitle}>{post.title}</Text><View style={styles.topMeta}><PlatformBadge platform={post.platform} compact /><Text style={styles.topStat}>{post.views ?? `${(18 - index * 4).toFixed(1)}k`} views</Text></View></View><Text style={styles.topEngagement}>{post.engagement ?? `${7.3 - index * 1.2}%`}</Text></View>)}</View></ScrollView></View>;
}
const styles = StyleSheet.create({ eyebrow: { color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.1, paddingTop: spacing.sm, marginBottom: 7 }, subtitle: { color: colors.muted, fontSize: 14, marginTop: 7, marginBottom: spacing.lg }, filters: { gap: 8, marginBottom: spacing.lg }, filter: { overflow: 'hidden', color: colors.muted, backgroundColor: colors.surface, borderRadius: radius.pill, paddingHorizontal: 14, paddingVertical: 9, fontSize: 12, fontWeight: '700' }, filterActive: { backgroundColor: colors.ink, color: colors.surface }, metrics: { flexDirection: 'row', gap: 12, marginBottom: spacing.md }, chartCard: { backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.md, marginBottom: spacing.xl }, chartHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, cardLabel: { color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, chartValue: { color: colors.ink, fontSize: 24, fontWeight: '800', marginTop: 7 }, chartChange: { color: colors.green, fontSize: 12 }, range: { flexDirection: 'row', gap: 10, backgroundColor: colors.canvas, borderRadius: 10, padding: 5 }, rangeActive: { color: colors.accent, fontSize: 10, fontWeight: '800', backgroundColor: colors.surface, borderRadius: 6, paddingHorizontal: 6, paddingVertical: 4 }, rangeText: { color: colors.muted, fontSize: 10, paddingHorizontal: 3, paddingVertical: 4 }, topPosts: { backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.md }, topPost: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.line }, rank: { color: colors.subtle, fontSize: 12, fontWeight: '800', width: 28 }, topCopy: { flex: 1 }, topTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' }, topMeta: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 7 }, topStat: { color: colors.muted, fontSize: 11 }, topEngagement: { color: colors.green, fontSize: 12, fontWeight: '800' } });
